### PR TITLE
This should fix #181

### LINKED ISSUE #181: sp.disable_function.function and value_r not working as expected
PHP version 7.1
Latest git combined.

I'm trying to determine if I am mis-understanding this or it is not working.

There are these default rules included:

```python
sp.disable_function.function("require_once").value_r("\.php$").allow();
sp.disable_function.function("include_once").value_r("\.php$").allow();
sp.disable_function.function("require").value_r("\.php$").allow();
sp.disable_function.function("include").value_r("\.php$").allow();
sp.disable_function.function("require_once").drop()
sp.disable_function.function("include_once").drop()
sp.disable_function.function("require").drop()
sp.disable_function.function("include").drop()
```

I expected include functions to be denied that did not end in `.php$`. To test I attempted to include a file called test.ico which was allowed. I also tried the reverse just to block `.ico` (with similation)

```python
sp.disable_function.function("require_once").value_r("\.ico$").drop().simulation();
sp.disable_function.function("include_once").value_r("\.ico$").drop().simulation();
sp.disable_function.function("require").value_r("\.ico$").drop().simulation();
sp.disable_function.function("include").value_r("\.ico$").drop().simulation();
```

Doing the above blocks all include calls, not just those ending with `.ico`.

### PR DESCRIPTION
**Pull request by kkadosh**

### CODE REVIEW

File: src/sp_disabled_functions.c [hunk 1]
```diff
@@ -248,6 +248,28 @@ static zend_execute_data* is_file_matching(
...
+bool check_is_builtin_without_param(sp_disabled_function const* const config_node) {
+    if (config_node->function) {
+      if  (!strcmp(config_node->function, "include") ||
+         !strcmp(config_node->function, "include_once") ||
+         !strcmp(config_node->function, "require") ||
+         !strcmp(config_node->function, "require_once")) {
+         return true;
+      }
+    }
+    if (config_node->r_function) {
```
Comment (jvoisin) [inline src/sp_disabled_functions.c]: Please use an `else if` here

File: src/sp_disabled_functions.c [hunk 2]
```diff
@@ -248,6 +248,28 @@ static zend_execute_data* is_file_matching(
 #undef ITERATE
 }
 
+
+bool check_is_builtin_without_param(sp_disabled_function const* const config_node) {
```
Comment (jvoisin) [inline src/sp_disabled_functions.c]: What about `is_builtin_function_name` instead?

Comment (jvoisin) [inline src/sp_disabled_functions.c]: I think that this function might be `static`, and maybe `inline` too.

File: src/sp_disabled_functions.c [hunk 3]
```diff
@@ -248,6 +248,28 @@ static zend_execute_data* is_file_matching(
 #undef ITERATE
 }
 
+
+bool check_is_builtin_name(sp_disabled_function const* const config_node) {
```
Comment (jvoisin) [inline src/sp_disabled_functions.c]: I think that this function could be `static` and `inline`.

File: src/sp_disabled_functions.c [hunk 4]
```diff
@@ -360,8 +379,19 @@ bool should_disable(zend_execute_data* execute_data, const char* builtin_name,
       }
     }
 
-    /* Everything matched.*/
+    if (config_node->value_r || config_node->value)
+    {
+      bool is_builtin = check_is_builtin_name(config_node);
```
Comment (jvoisin) [inline src/sp_disabled_functions.c]: No need for a variable here in my opinion.
